import { NavLink } from "react-router-dom";

const NavBar = () => {
    return(
        <>
        <nav>
            <ul>
                <li>
                    <NavLink
                    to='/'>
                        ShopReny
                    </NavLink>
                </li>
                <li>
                    <NavLink
                    to='/'>
                        All
                    </NavLink>
                </li>
                <li>
                    <NavLink
                    to='/'>
                        Clothes
                    </NavLink>
                </li>
                <li>
                    <NavLink
                    to='/'>
                        Electronics
                    </NavLink>
                </li>
                <li>
                    <NavLink
                    to='/'>
                        Fornitures
                    </NavLink>
                </li>
                <li>
                    <NavLink
                    to='/'>
                        Toys
                    </NavLink>
                </li>
            </ul>
        </nav>
        </>
    )
}